<a href="https://colab.research.google.com/github/sheldonkemper/portfolio/blob/main/CAM_DS_C201_Activity_3_3_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Activity 3.3.6 Exploring evaluation metrics

## Scenario
Hopkins et al. (1999) created the Spambase data set donated to the UCI Machine Learning Repository. The data set contains 4,601 emails marked as spam or non-spam by a postmaster or individuals. Fifty-seven features aid in classifying emails as spam (e.g. word frequencies and email characteristics). The Spambase data set is used for developing and benchmarking spam detection models, providing a base for analysing the effectiveness of various machine learning techniques in distinguishing between spam and legitimate emails.

As a data professional, you were tasked by your company to develop a neural network with TensorFlow that can classify emails as spam or non-spam. You were tasked to develop a model based on the Spambase data set.



## Objective
In this portfolio activity, you’ll continue to work with the model you created in Activity 3.2.3: Experimenting with hyperparameter tuning by applying evaluation metrics and a pre-trained model to classify emails as spam or non-spam.

You will complete the activity in your Notebook, where you’ll:
- choose the best model based on model performance
- make predictions based on the chosen model
- convert probabilities to binary predictions and view accuracy, F1 score, and recall
- present your insights based on the model's performance.


## Assessment criteria
By completing this activity, you will be able to provide evidence that you can critically select appropriate strategies to demonstrate expertise in model-tuning techniques.


## Activity guidance
1. Continue to work on the model you created in **Activity 3.2.3**.
2. Select the best model you obtained through hyperparameter tuning. Substantiate your choice.
3. Run the chosen model again and save it in an `h5` file named `best_model.h5`. Remember to specify the path.
4. Check further metrics for the model with the predict function applied to your model variable in order to create predictions on the `X_test` data set.
5. Convert probabilities to binary predictions and print the accuracy, F1 score, and recall. You can use the following code:
 - predictions: `y_pred = (y_pred > 0.5).astype(int)`
 - confusion matrix metrics: `accuracy_score`, `precision_score`, `recall_score` and `f1_score` functions.

In [10]:
import keras
from keras import layers
import tensorflow as tf
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [11]:
# Start your activity here:

# URL to import data set from GitHub.
url = 'https://raw.githubusercontent.com/fourthrevlxd/cam_dsb/main/spamdata.csv'
data = pd.read_csv(url, header = None)
data.head()

0     1     2    3     4     5     6     7     8     9   ...    48  \
0  0.00  0.64  0.64  0.0  0.32  0.00  0.00  0.00  0.00  0.00  ...  0.00   
1  0.21  0.28  0.50  0.0  0.14  0.28  0.21  0.07  0.00  0.94  ...  0.00   
2  0.06  0.00  0.71  0.0  1.23  0.19  0.19  0.12  0.64  0.25  ...  0.01   
3  0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...  0.00   
4  0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...  0.00   

      49   50     51     52     53     54   55    56  57  
0  0.000  0.0  0.778  0.000  0.000  3.756   61   278   1  
1  0.132  0.0  0.372  0.180  0.048  5.114  101  1028   1  
2  0.143  0.0  0.276  0.184  0.010  9.821  485  2259   1  
3  0.137  0.0  0.137  0.000  0.000  3.537   40   191   1  
4  0.135  0.0  0.135  0.000  0.000  3.537   40   191   1  

[5 rows x 58 columns]

In [12]:
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

# Split into train and test sets (80% train, 20% test)
X_train_full, X_test, y_train_full, y_test = train_test_split(X ,y, test_size=0.2, random_state = 42)
# Further split the training set into train and validation (90% train, 10% validation)
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full, test_size=0.1, random_state = 42)

# Scale the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_valid)
X_test = scaler.transform(X_test)

### Run the Chosen Model and Save It:


In [13]:
# Rebuild the model with batch size of 64 and 30 epochs
model = tf.keras.Sequential()

# Define the layers
model.add(tf.keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(16, activation='relu'))

# Output layer for binary classification
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

# Compile the model
model.compile(optimizer=tf.keras.optimizers.Adam(),
              loss=tf.keras.losses.BinaryCrossentropy(),
              metrics=['accuracy'])

# Train the model with the best hyperparameters
model.fit(X_train, y_train, epochs=30, batch_size=64, validation_data=(X_valid, y_valid))

# Save the model to an h5 file
model.save('my_model.keras')


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/30
52/52 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.6193 - loss: 0.6282 - val_accuracy: 0.8804 - val_loss: 0.4025
Epoch 2/30
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9021 - loss: 0.3369 - val_accuracy: 0.9266 - val_loss: 0.1965
Epoch 3/30
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9399 - loss: 0.1805 - val_accuracy: 0.9348 - val_loss: 0.1831
Epoch 4/30
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9477 - loss: 0.1443 - val_accuracy: 0.9402 - val_loss: 0.1890
Epoch 5/30
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9409 - loss: 0.1486 - val_accuracy: 0.9402 - val_loss: 0.1850
Epoch 6/30
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9568 - loss: 0.1218 - val_accuracy: 0.9266 - val_loss: 0.1858
Epoch 7/30
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9568 - loss: 0.1253 - val_accuracy: 0.9321 - val_loss: 0.2013
Epoch 8/30
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9650 - loss: 0.1049 - val_accuracy: 0.9375 - val_loss:

The best model I obtained through hyperparameter tuning was the one with **batch size of 64** and **30 epochs**.

I chose this model because it achieved the highest **test accuracy** of **95.01%** during the tuning process, making it the most effective at classifying emails as spam or non-spam. Although there was some overfitting (reflected by a higher validation loss), this model demonstrated the most consistent performance across the training, validation, and test sets.

After evaluating further metrics, the model showed strong results, with an **accuracy of 95.55%**, **precision of 95.32%**, **recall of 94.10%**, and an **F1 score of 94.71%**. These balanced metrics confirmed that it not only catches spam effectively but also minimises false positives and negatives.

Based on this overall performance, I selected this model as the best one from the tuning process.

### Create Predictions Using the predict Function


In [14]:
# Generate predictions (probabilities) on the test set
y_pred = model.predict(X_test)

29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step


### Convert Probabilities to Binary Predictions:

In [15]:
# Convert probabilities to binary predictions
y_pred = (y_pred > 0.5).astype(int)

## Evaluate Further Metrics

In [16]:
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

# Calculate precision
precision = precision_score(y_test, y_pred)

# Calculate recall
recall = recall_score(y_test, y_pred)

# Calculate F1 score
f1 = f1_score(y_test, y_pred)

# Print the results
print(f'Accuracy: {accuracy:.4f}')
print(f'Precision: {precision:.4f}')
print(f'Recall: {recall:.4f}')
print(f'F1 Score: {f1:.4f}')


Accuracy: 0.9555
Precision: 0.9532
Recall: 0.9410
F1 Score: 0.9471


Here’s a quick summary of the performance metrics for my model:

- **Accuracy: 95.55%** – Overall, the model correctly classified 95.55% of emails as either spam or non-spam.
- **Precision: 95.32%** – Out of all the emails the model predicted as spam, 95.32% were actually spam. A high precision means there were fewer false positives.
- **Recall: 94.10%** – The model correctly identified 94.10% of actual spam emails. This shows the model is good at catching most spam, though it might miss a few.
- **F1 Score: 94.71%** – The F1 score balances precision and recall, and in this case, it shows the model performs well across both metrics.

### Conclusion:
The model is performing very well, with a balanced precision, recall, and overall accuracy. Based on these results, I’m confident it would be reliable in a real-world spam detection task.

# Reflect

Write a brief paragraph highlighting your process and the rationale to showcase critical thinking and problem-solving.

In this project, my goal was to optimise a spam detection model using TensorFlow by experimenting with various hyperparameters. I began by tuning the **batch size** and **epochs**, testing multiple combinations to identify which setup yielded the best accuracy without overfitting. After selecting the optimal configuration (batch size of 64 and 30 epochs), I evaluated the model's performance based on key metrics like **accuracy**, **precision**, **recall**, and the **F1 score**. While fine-tuning the model, I paid close attention to the trade-off between precision (minimising false positives) and recall (catching the most spam emails), ultimately aiming for a balanced model that would generalise well to new data. This iterative approach reflects my focus on critical thinking and problem-solving, balancing model complexity with performance.

# References

Hopkins, M., Reeber, E., Forman, G., Suermondt, J., 1999. Spambase. [online]. Available at: https://archive.ics.uci.edu/dataset/94. [Accessed 5 March 2024].